aoi_kw_dict_v1 = {
    'tongzha': "tongzha",
    'zawu_qing': 'zawu_qing',
    'zawu_zhong': 'zawu_zhong',
    'quekou': 'quekou',
    # 'maobianweiduan': 'maobianweiduan',
    # 'maobianweiduan_qing': 'maobianweiduan_qing',
    'guahua': 'guahua',
    'yise': 'yise',
    'bansun': 'bansun',
    'quetong': 'quetong',
    'youmo_lv': 'youmo_lv',
    'youmo_lan': 'youmo_lan',
    'jiaomo': 'jiaomo',
    'banbian': 'banbian',
    'qipao': 'qipao',
    '铜渣': 'tongzha',
    '板损': 'bansun',
    '刮花': 'guahua',
    '微短': 'tongzha',
    '杂物_轻': 'zawu_qing',
    '杂物_重': 'zawu_zhong',
    '缺口': 'quekou',
    '针孔': 'quekou',
    '缺铜': 'quetong',
    '毛边微短': 'maobianweiduan_qing',
    '毛边微短_重': 'maobianweiduan',
    '氧化': 'yanghua',
    '氧化_轻': 'yanghua',
    '氧化_重': 'yanghua',
    '油墨_蓝': 'youmo_lan',
    '油墨_绿': 'youmo_lv',
    '异色': 'yise',
    '胶膜': 'jiaomo',
    '气泡': 'qipao',
    '板边': 'banbian',
    'weiduan': 'tongzha',

    '杂物重': 'zawu_zhong',
    '杂物轻': 'zawu_qing',
    '杂物-重': 'zawu_zhong',
    '油墨蓝': 'youmo_lan',
    '毛边单': 'maobiandan',

    '2': 'tongzha',
    'tutong': 'tongzha',
    'tongza': 'tongzha',

    'zawu': 'zawu_qing',
    'zawu_0': 'zawu_qing',
    'zawu_1': 'zawu_zhong',

    'duankai': 'quekou',

    'zhenkong': 'quekou',
    'quokou': 'quekou',

    'zawuz_zhong': 'zawu_zhong',
    'yangahua': 'zhenkong',

    # 'miaobianweiduan': 'maobianweiduan',
    # 'maobian_weiduan':'maobianweiduan',

    'guashang': 'guahua',

    'yanghua': 'yanghua',
    'yanghau': 'yanghua',

    'youmolan': 'youmo_lan',
    'youmo_lu': 'youmo_lv',
    'kongbian': 'banbian',
    '夹角铜渣': 'jiajiaotongzha',
    'jiajiaotongzha': 'jiajiaotongzha',

    # 外层
    'tongkong': 'tongkong',
    'kongpo': 'kongpo',
    'kongneitongzha': 'kongneitongzha',
    'mangkong': 'mangkong',
    'jiajiaotongzha': 'jiajiaotongzha',
    'kongbianpifeng': 'kongbianpifeng',
    'jiamo': 'jiamo',
    '通孔': 'tongkong',
    '孔破': 'kongpo',
    '孔内铜渣': 'kongneitongzha',
    '盲孔': 'mangkong',
    '夹角铜渣': 'jiajiaotongzha',
    '孔边披风': 'kongbianpifeng',
    '荚膜': 'jiamo'

}
reverse_aoi_kw_dict_v1 = {
    'bansun': '板损',
    'guahua': '刮花',
    'zawu_qing': '杂物轻',
    'zawu_zhong': '杂物-重',
    'quekou': '针孔',
    'quetong': '缺铜',
    'maobianweiduan_qing': '毛边微短',
    'maobianweiduan': '毛边微短_重',
    'yanghua': '氧化_重',
    'youmo_lan': '油墨蓝',
    'youmo_lv': '油墨_绿',
    'yise': '异色',
    'jiaomo': '胶膜',
    'qipao': '气泡',
    'banbian': '板边',
    'maobiandan': '毛边单',
    'jiajiaotongzha': '夹角铜渣',
    'tongkong': '通孔',
    'kongpo': '孔破',
    'kongneitongzha': '孔内铜渣',
    'mangkong': '盲孔',
    'kongbianpifeng': '孔边披风',
    'jiamo': '荚膜'
}

# 设置一个anno_pair_cfg, 用于毛边pair的匹配
anno_pair_cfg_v1 = {
    "match_reg_name": r"毛边微短[1-9]|1[0-9]|2[0-9]",
    "change_dict_name": "毛边微短"
}

aoi_kw_dict_v2 = {
    '板损': 'bansun',
    '微短': 'weiduan',
    '缺口': 'quekou',
    '针孔': 'zhenkong',
    'zhenkong': 'zhenkong',
    'banbian': 'banbian',
    '铜渣': 'tongzha',
    '毛边微短': 'maobianweiduan',
    '毛边': 'maobianweiduan_qing',
    '油墨_蓝': 'youmo_lan',
    '油墨_绿': 'youmo_lv',
    '胶膜': 'jiaomo',
    '气泡': 'qipao',
    '板边': 'banbian',
    '盲孔': 'mangkong',
    '夹角铜渣': 'jiajiaotongzha',
    '毛边单': 'maobiandan',
    '氧化_彩色': 'yanghua_cai',
    '氧化_擦伤': 'yanghua_cashang',
    '氧化_点群': 'yanghua_qun',
    '氧化_擦伤_红光': 'yanghua_hongguang',
    '氧化_水泽': 'yanghua_shuize',
    '氧化_严重': 'yanghua_zhong',
    '氧化_轻微': 'yanghua_qing',
    '杂物_黑色': 'zawu_heise',
    '杂物_黑点': 'zawu_heidian',
    '杂物_点群': 'zawu_qun',
    '杂物_浅色透明': 'zawu_qiantou',
    '杂物_浅色不透': 'zawu_qianbutou',
    '开路': 'kailu',
    '缺铜_深色': 'quetong_shense',
    '缺铜_黑色凹坑': 'quetong_aokeng',
    '缺铜_均匀铜薄': 'quetong_junbao',
    '缺铜_破损': 'quetong_posun',
    '缺铜_刮痕均匀': 'quetong_guahen',
    '缺铜_边缘铜薄': 'quetong_bianbao',
    '缺铜_浅色': 'quetong_qianse',
    '缺铜_不均匀': 'quetong_bujun',
    '缺铜_折痕': 'quetong_zhehen',
    '刮花_发亮': 'gauhua_liang',
    '刮花_损伤': 'guahua_shang',
    '铜渣_铜上凸铜': 'tong_tutong',
    '铜渣_铜上铜丝': 'tong_tongsi',
    '铜渣_蚀刻未尽': 'tong_shike',

    # 外层
    # 'tongkong': 'tongkong',
    # 'kongpo': 'kongpo',
    # 'kongneitongzha': 'kongneitongzha',
    # 'mangkong': 'mangkong',
    # 'jiajiaotongzha': 'jiajiaotongzha',
    # 'kongbianpifeng': 'kongbianpifeng',
    # 'jiamo': 'jiamo',
    # '通孔': 'tongkong',
    # '孔破': 'kongpo',
    # '孔内铜渣': 'kongneitongzha',
    # '盲孔': 'mangkong',
    # '夹角铜渣': 'jiajiaotongzha',
    # '孔边披风': 'kongbianpifeng',
    # '荚膜': 'jiamo',
    # '蓝光杂物': 'languangzawu',
    # '退锡不净': 'bujing',
    #细分
    # avi
    # '保护膜': 'baohumo',
    # '保胶重叠': 'baojiaochongdie',
    # '碎屑': 'suixie'
}
reverse_aoi_kw_dict_v2 = {
    'bansun': '板损',
    'weiduan': '微短',
    'quekou': '缺口',
    'zhenkong': '针孔',
    'tongzha': '铜渣',
    'maobianweiduan': '毛边微短',
    'maobianweiduan_qing': '毛边',
    'youmo_lan': '油墨_蓝',
    'youmo_lv': '油墨_绿',
    'jiaomo': '胶膜',
    'qipao': '气泡',
    'banbian': '板边',
    'mangkong': '盲孔',
    'jiajiaotongzha': '夹角铜渣',
    'maobiandan': '毛边单',
    'yanghua_cai': '氧化_彩色',
    'yanghua_cashang': '氧化_擦伤',
    'yanghua_qun': '氧化_点群',
    'yanghua_hongguang': '氧化_擦伤_红光',
    'yanghua_shuize': '氧化_水泽',
    'yanghua_zhong': '氧化_严重',
    'yanghua_qing': '氧化_轻微',
    'zawu_heise': '杂物_黑色',
    'zawu_heidian': '杂物_黑点',
    'zawu_qun': '杂物_点群',
    'zawu_qiantou': '杂物_浅色透明',
    'zawu_qianbutou': '杂物_浅色不透',
    'kailu': '开路',
    'quetong_shense': '缺铜_深色',
    'quetong_aokeng': '缺铜_黑色凹坑',
    'quetong_junbao': '缺铜_均匀铜薄',
    'quetong_posun': '缺铜_破损',
    'quetong_guahen': '缺铜_刮痕均匀',
    'quetong_bianbao': '缺铜_边缘铜薄',
    'quetong_qianse': '缺铜_浅色',
    'quetong_bujun': '缺铜_不均匀',
    'quetong_zhehen': '缺铜_折痕',
    'gauhua_liang': '刮花_发亮',
    'guahua_shang': '刮花_损伤',
    'tong_tutong': '铜渣_铜上凸铜',
    'tong_tongsi': '铜渣_铜上铜丝',
    'tong_shike': '铜渣_蚀刻未尽'
}

anno_pair_cfg_v2 = {
    "match_reg_name": r"毛边(?:微短)?[1-9]|1[0-9]|2[0-9]",
    "change_dict_name": "毛边"
}


aoi_kw_dict_v3 = {
    'tongzha': "tongzha",
    'zawu_qing': 'zawu_qing',
    'zawu_zhong': 'zawu_zhong',
    'quekou': 'quekou',
    # 'maobianweiduan': 'maobianweiduan',
    # 'maobianweiduan_qing': 'maobianweiduan_qing',
    'guahua': 'guahua',
    'yise': 'yise',
    'bansun': 'bansun',
    'quetong': 'quetong',
    'youmo_lv': 'youmo_lv',
    'youmo_lan': 'youmo_lan',
    'jiaomo': 'jiaomo',
    'banbian': 'banbian',
    'qipao': 'qipao',
    '铜渣': 'tongzha',
    '板损': 'bansun',
    '刮花': 'guahua',
    '微短': 'tongzha',
    '杂物_轻': 'zawu_qing',
    '杂物_重': 'zawu_zhong',
    '缺口': 'quekou',
    '针孔': 'quekou',
    '缺铜': 'quetong',
    '毛边微短': 'maobianweiduan',
    '毛边微短_重': 'maobianweiduan',
    '毛边': 'maobianweiduan_qing',
    '氧化': 'yanghua',
    '氧化_轻': 'yanghua',
    '氧化_重': 'yanghua',
    '油墨_蓝': 'youmo_lan',
    '油墨_绿': 'youmo_lv',
    '异色': 'yise',
    '胶膜': 'jiaomo',
    '气泡': 'qipao',
    '板边': 'banbian',
    'weiduan': 'tongzha',

    '杂物重': 'zawu_zhong',
    '杂物轻': 'zawu_qing',
    '杂物-重': 'zawu_zhong',
    '油墨蓝': 'youmo_lan',
    '毛边单': 'maobiandan',

    '2': 'tongzha',
    'tutong': 'tongzha',
    'tongza': 'tongzha',

    'zawu': 'zawu_qing',
    'zawu_0': 'zawu_qing',
    'zawu_1': 'zawu_zhong',

    'duankai': 'quekou',

    'zhenkong': 'quekou',
    'quokou': 'quekou',

    'zawuz_zhong': 'zawu_zhong',
    'yangahua': 'zhenkong',

    # 'miaobianweiduan': 'maobianweiduan',
    # 'maobian_weiduan':'maobianweiduan',

    'guashang': 'guahua',

    'yanghua': 'yanghua',
    'yanghau': 'yanghua',

    'youmolan': 'youmo_lan',
    'youmo_lu': 'youmo_lv',
    'kongbian': 'banbian',
    '夹角铜渣': 'jiajiaotongzha',
    'jiajiaotongzha': 'jiajiaotongzha',

    # 外层
    # 'tongkong': 'tongkong',
    # 'kongpo': 'kongpo',
    # 'kongneitongzha': 'kongneitongzha',
    # 'mangkong': 'mangkong',
    # 'jiajiaotongzha': 'jiajiaotongzha',
    # 'kongbianpifeng': 'kongbianpifeng',
    # 'jiamo': 'jiamo',
    # '通孔': 'tongkong',
    # '孔破': 'kongpo',
    # '孔内铜渣': 'kongneitongzha',
    # '盲孔': 'mangkong',
    # '夹角铜渣': 'jiajiaotongzha',
    # '孔边披风': 'kongbianpifeng',
    # '荚膜': 'jiamo',
    # '蓝光杂物': 'languangzawu',
    # '退锡不净': 'bujing',
    #细分
    '氧化_彩色': 'yanghua',
    '氧化_擦伤': 'yanghua',
    '氧化_点群': 'yanghua',
    '氧化_擦伤_红光': 'yanghua',
    '氧化_水泽': 'yanghua',
    '氧化_严重': 'yanghua',
    '氧化_轻微': 'yanghua',
    '杂物_黑色': 'quekou',
    '杂物_黑点': 'zawu_qing',
    '杂物_浅色不透': 'zawu_zhong',
    '杂物_浅色透明': 'zawu_qing',
    '杂物_点群': 'zawu_qing',
    '开路': 'quekou',
    '缺铜_深色': 'quetong',
    '缺铜_黑色凹坑': 'quetong',
    '缺铜_均匀铜薄': 'quetong',
    '缺铜_破损': 'quetong',
    '缺铜_刮痕均匀': 'quetong',
    '缺铜_边缘铜薄': 'quetong',
    '缺铜_浅色': 'quetong',
    '缺铜_不均匀': 'quetong',
    '缺铜_折痕': 'quetong',
    '刮花_发亮': 'guahua',
    '刮花_损伤': 'guahua',
    '铜渣_铜上凸铜': 'tongzha',
    '铜渣_铜上铜丝': 'tongzha',
    '铜渣_蚀刻未尽': 'tongzha',
    '孔壁': 'maobiandan',

    # avi
    # '保护膜': 'baohumo',
    # '保胶重叠': 'baojiaochongdie',
    # '碎屑': 'suixie'

}
reverse_aoi_kw_dict_v3 = {
    'tongzha': '铜渣_蚀刻未尽',
    'bansun': '板损',
    'guahua': '刮花_损伤',
    'zawu_qing': '杂物_点群',
    'zawu_zhong': '杂物_浅色不透',
    'quekou': '开路',
    'quetong': '缺铜_折痕',
    'maobianweiduan': '毛边微短_重',
    'maobianweiduan_qing': '毛边',
    'yanghua': '氧化_轻微',
    'youmo_lan': '油墨蓝',
    'youmo_lv': '油墨_绿',
    'yise': '异色',
    'jiaomo': '胶膜',
    'qipao': '气泡',
    'banbian': '板边',
    'maobiandan': '孔壁',
    'jiajiaotongzha': '夹角铜渣'
}
# 设置一个anno_pair_cfg, 用于毛边pair的匹配
anno_pair_cfg_v3 = {
    "match_reg_name": r"毛边(?:微短)?[1-9]|1[0-9]|2[0-9]",
    "change_dict_name": "毛边"
}

aoi_kw_dict_v4 = {
    '板损': 'bansun',
    '微短': 'weiduan',
    '缺口': 'quekou',
    '针孔': 'zhenkong',
    '铜渣': 'tongzha',
    '毛边微短': 'maobianweiduan',
    '毛边': 'maobianweiduan_qing',
    '油墨_蓝': 'youmo_lan',
    '油墨_绿': 'youmo_lv',
    '胶膜': 'jiaomo',
    '气泡': 'qipao',
    '板边': 'banbian',
    '盲孔': 'mangkong',
    '夹角铜渣': 'jiajiaotongzha',
    '毛边单': 'maobiandan',
    '氧化_彩色': 'yanghua',
    '氧化_擦伤': 'yanghua',
    '氧化_点群': 'yanghua',
    '氧化_擦伤_红光': 'yanghua',
    '氧化_水泽': 'yanghua',
    '氧化_严重': 'yanghua',
    '氧化_轻微': 'yanghua',
    '杂物_黑色': 'zawu',
    '杂物_黑点': 'zawu',
    '杂物_点群': 'zawu',
    '杂物_浅色透明': 'zawu',
    '杂物_浅色不透': 'zawu',
    '开路': 'kailu',
    '缺铜_深色': 'quetong',
    '缺铜_黑色凹坑': 'quetong',
    '缺铜_均匀铜薄': 'quetong',
    '缺铜_破损': 'quetong',
    '缺铜_刮痕均匀': 'quetong',
    '缺铜_边缘铜薄': 'quetong',
    '缺铜_浅色': 'quetong',
    '缺铜_不均匀': 'quetong',
    '缺铜_折痕': 'quetong',
    '刮花_发亮': 'gauhua',
    '刮花_损伤': 'guahua',
    '铜渣_铜上凸铜': 'tong',
    '铜渣_铜上铜丝': 'tong',
    '铜渣_蚀刻未尽': 'tong',

    # 外层
    # 'tongkong': 'tongkong',
    # 'kongpo': 'kongpo',
    # 'kongneitongzha': 'kongneitongzha',
    # 'mangkong': 'mangkong',
    # 'jiajiaotongzha': 'jiajiaotongzha',
    # 'kongbianpifeng': 'kongbianpifeng',
    # 'jiamo': 'jiamo',
    # '通孔': 'tongkong',
    # '孔破': 'kongpo',
    # '孔内铜渣': 'kongneitongzha',
    # '盲孔': 'mangkong',
    # '夹角铜渣': 'jiajiaotongzha',
    # '孔边披风': 'kongbianpifeng',
    # '荚膜': 'jiamo',
    # '蓝光杂物': 'languangzawu',
    # '退锡不净': 'bujing',
    #细分
    # avi
    # '保护膜': 'baohumo',
    # '保胶重叠': 'baojiaochongdie',
    # '碎屑': 'suixie'
}
reverse_aoi_kw_dict_v4 = {
    'bansun': '板损',
    'weiduan': '微短',
    'quekou': '缺口',
    'zhenkong': '针孔',
    'tongzha': '铜渣',
    'maobianweiduan': '毛边微短',
    'maobianweiduan_qing': '毛边',
    'youmo_lan': '油墨_蓝',
    'youmo_lv': '油墨_绿',
    'jiaomo': '胶膜',
    'qipao': '气泡',
    'banbian': '板边',
    'mangkong': '盲孔',
    'jiajiaotongzha': '夹角铜渣',
    'maobiandan': '毛边单',
    'yanghua': '氧化_轻微',
    'zawu': '杂物_浅色不透',
    'kailu': '开路',
    'quetong': '缺铜_折痕',
    'gauhua': '刮花_发亮',
    'guahua': '刮花_损伤',
    'tong': '铜渣_蚀刻未尽'
}
anno_pair_cfg_v4 = {
    "match_reg_name": r"毛边(?:微短)?[1-9]|1[0-9]|2[0-9]",
    "change_dict_name": "毛边"
}

# 新加的配置，都要在这里注册
mapping_cfg_dict = {
    "v1": (anno_pair_cfg_v1, aoi_kw_dict_v1, reverse_aoi_kw_dict_v1),
    "v2": (anno_pair_cfg_v2, aoi_kw_dict_v2, reverse_aoi_kw_dict_v2),
    "v3": (anno_pair_cfg_v3, aoi_kw_dict_v3, reverse_aoi_kw_dict_v3),
    "v4": (anno_pair_cfg_v4, aoi_kw_dict_v4, reverse_aoi_kw_dict_v4),
}
